Setup ESlint and Prettier for linting
megabit-labs/pathways pull request #23
Opened 2020-07-09 06:28 UTC by jshreyans

Added rules that were required to ensure a standard code style throughout the project. Right now ESlint is configured only in the `client` folder and uses the Airbnb style guide, which, in my opinion, is decent for React. 

For linting, I've added 3 scripts to `package.json`, out of which the second one should be used every time someone has finished making changes and are about to commit them. These scripts are:
- `lint`: only *display* linting errors
- `lint:fix`: *fixes* all linting errors
- `format`: triggers Prettier and displays formatting errors

2020-07-09 06:44 UTC, twitu commented
Consider adding something similar for the `server` directory as well.

2020-07-09 15:48 UTC, dusnat requested changes
@jshreyans add this file to the repo root, so that the server-side guys can also use the same style rules. Or if these rules are good only for React, please add something appropriate for the server side code too (which is just simple nodejs code), like @twitu suggests.

2020-07-10 07:30 UTC, jshreyans commented
I've added a separate eslint config to the `server` directory. It uses almost entirely the same rules as the client-side setup. Linting scripts are available too.

2020-07-10 09:13 UTC, dush-t commented
Can the formatting be "triggered" through the vscode shortcut (Ctrl + Shift + i)? Also, can you include a script that auto-formats the code (instead of linting it)?

2020-07-10 09:29 UTC, jshreyans commented
> Can the formatting be "triggered" through the vscode shortcut (Ctrl + Shift + i)?

Will have to look into this. Although I guess if you have the Prettier extension installed, it should automatically pick up rules defined in `.prettierrc` and format code. Then you can use whatever shortcut you've configured like Ctrl+Shift+I.

> Also, can you include a script that auto-formats the code (instead of linting it)?

It's already there. The `format` script does this exactly.

2020-07-10 09:37 UTC, jshreyans commented
Also, the pre-commit hook is now working. It uses `husky` to run the hook and `lint-staged` to lint only those files that have been staged for that commit, instead of the entire project (which would have been redundant). 

A heads up, you might get unexpected errors when these hooks run. The way its configured is that when you try to commit, the linter will run on the staged files and will resolve almost all major errors (tried and tested on several files). However, it might not be able to handle some errors. For example, if there are dependencies that have been used in the code but have not been installed. These are errors that require manual review and ESlint will **not** take care of them. Once you resolve these and try to run the commit, it works well (again, tried and tested).

2020-07-11 09:53 UTC, dusnat approved these changes

2020-07-11 09:54 UTC, merged